### ISSUE TITLE
Download site: Registration broken

### ISSUE THREAD

**Issue by Erudition** [eighty20results/pmpro-sequence#15]
It looks like the canonical place to download the plugin is this blog post
https://eighty20results.com/wordpress-plugins/e20r-sequences/
where the link to download is buried wayyy at the bottom. It requires registration to proceed.
However, on page 5 of the registration/checkout process:
https://eighty20results.com/account/checkout/?level=5
...and after filling in all the visible fields, I am unable to continue - because hitting "continue" just adds this error to the page: "Please provide your opt-in selection". Which makes no sense, because there is no unfilled field remaining.

Side note: It's a shame that we can't download this plugin from the wordpress plugin directory - that would let me enable automatic updates. With the current process I'd have to manually check for - let alone install - updates.

Anyway, downloading the ZIP from github works for now.

**Comment by eighty20results** [comment]
Thank you for the heads up on the registration page. WIll take a look and resolve.

Since this isn't a bug with the plugin itself, I'm going to close this report
