### ISSUE TITLE
Plugin Abandoned?

### ISSUE THREAD

**Issue by Erudition** [eighty20results/pmpro-sequence#16]
Hi there, I just started using this plugin in my site, but I found that the "support forum" linked from the about page, does not exist. In fact, several links on that page are broken, including the premium upgrade for this addon... What's going on? I also notice that the Trello board hasn't shown any activity since 2018, and there are still a lot of open feature cards.

Should I be avoiding using this on a production site? Will it still work with modern Wordpress?

**Comment by eighty20results** [comment]
It's ceratainly not abandoned. 

I have it running on a couple of my own sites, on the current release of WordPress and with the current release of PMPro. Everything is working as I designed it to work, so I haven't felt the need to spend time on updating it.
